#!/bin/bash

# ✅ Enable debugging mode based on a condition
if [ 0 -gt 0 ]; then
    set -x
else
    set -v
fi

# ✅ Ensure the script exits on error
set -eu
set -o pipefail

echo "[INFO] Cleaning up GRUB2 temporary files..."
rm -rf /var/cache/dnf/* /var/cache/apt/* /boot/grub2/grubenv /boot/grub/grubenv
