#!/bin/bash

# ✅ Enable debugging mode based on a condition
if [ 0 -gt 0 ]; then
    set -x
else
    set -v
fi

# ✅ Ensure the script exits on error
set -eu
set -o pipefail

echo "Create ipa-rescue-config directory and file"
mkdir /etc/ipa-rescue-config
touch /etc/ipa-rescue-config/ipa-rescue-password


echo "Adding message to /etc/issue"
cat > /etc/issue <<EOF
██████╗ ██████╗ ███████╗███╗   ██╗███████╗████████╗ █████╗  ██████╗██╗  ██╗
██╔═══██╗██╔══██╗██╔════╝████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝
██║   ██║██████╔╝█████╗  ██╔██╗ ██║███████╗   ██║   ███████║██║     █████╔╝
██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██╔═██╗
╚██████╔╝██║     ███████╗██║ ╚████║███████║   ██║   ██║  ██║╚██████╗██║  ██╗
 ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝

██╗██████╗  ██████╗ ███╗   ██╗██╗ ██████╗
██║██╔══██╗██╔═══██╗████╗  ██║██║██╔════╝
██║██████╔╝██║   ██║██╔██╗ ██║██║██║
██║██╔══██╗██║   ██║██║╚██╗██║██║██║
██║██║  ██║╚██████╔╝██║ ╚████║██║╚██████╗
╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝ ╚═════╝
EOF

# ✅ Allow password login for rescue user
echo "Modifying SSH configuration inside image..."
sed -i 's|PasswordAuthentication no|PasswordAuthentication yes|g' /etc/ssh/sshd_config
