#!/bin/bash

# ✅ Enable debugging mode based on a condition
if [ 0 -gt 0 ]; then
    set -x
else
    set -v
fi

# ✅ Ensure the script exits on error
set -eu
set -o pipefail

echo "[INFO] Installing GRUB2 Bootloader..."

if [[ -f /etc/redhat-release ]]; then
    DISTRO="centos"
elif [[ -f /etc/lsb-release || -f /etc/debian_version ]]; then
    DISTRO="ubuntu"
else
    echo "[ERROR] Unsupported distribution."
    exit 1
fi

# ✅ Install the grub
if [[ "$DISTRO" == "centos" ]]; then
    dnf install -y grub2 grub2-tools shim efibootmgr
elif [[ "$DISTRO" == "ubuntu" ]]; then
    apt-get update && apt-get install -y grub-efi-amd64 grub2-common
fi
