#!/bin/bash

# ✅ Enable debugging mode based on a condition
if [ 0 -gt 0 ]; then
    set -x
else
    set -v
fi

set -eu
set -o pipefail

if [[ "\$DISTRO_NAME" == "ubuntu" ]]; then
    apt update
    apt install -y ipmitool nvme-cli smartmontools lldpad pciutils
elif [[ "\$DISTRO_NAME" == "centos" ]]; then
    dnf check-update
    dnf install -y ipmitool nvme-cli smartmontools lldpad pciutils
fi
