#!/bin/bash

# Enable debugging mode based on a condition
if [ 0 -gt 0 ]; then
    set -x
else
    set -v
fi

# Ensure the script exits on error
set -eu
set -o pipefail

isRH=0

egrep -q -i 'Centos|RedHat' /etc/redhat-release 2>/dev/null && isRH=1

if [ $isRH -eq 1 ]; then
  echo "Enabling eno1 connection"

  #yum -y install snapd
  #systemctl enable --now snapd.socket
  #ln -s /var/lib/snapd/snap /snap
  #snap install netplan --edge --classic
  #snap list

  # DHCP is default IP method
cat << _EM1 > /etc/sysconfig/network-scripts/ifcfg-eno1
TYPE=Ethernet
BOOTPROTO=dhcp
NAME=eno1
DEVICE=eno1
ONBOOT=yes
_EM1

else

  mkdir -p /etc/netplan/

  cat << _NP > /etc/netplan/50-cloud-init.yaml
# This is the initial network config.
# It can be overwritten by cloud-init or console-conf.
network:
    version: 2
    ethernets:
        all-en:
            match:
                name: "en*"
            dhcp4: true
        all-eth:
            match:
                name: "eth*"
            dhcp4: true
_NP

fi
