#!/bin/bash

# Enable debugging mode based on a condition
if [ 0 -gt 0 ]; then
    set -x
else
    set -v
fi

# Ensure the script exits on error
set -eu
set -o pipefail

echo "Adding a script to run 'lsblk' upon user login"

# Create a profile script to execute the command at login
cat <<EOL > /etc/profile.d/show-disks.sh
#!/bin/bash
lsblk -Pbdi -oKNAME,SIZE,ROTA,SERIAL
EOL

# Ensure the script is executable
chmod +x /etc/profile.d/show-disks.sh
